[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'ozelentok/denite-gtags'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'vim-scripts/MultipleSearch'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'rgarver/Kwbd.vim'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'vim-scripts/BufOnly.vim'

[[plugins]]
repo = 'Shougo/deoplete-rct'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'iyuuya/denite-rails'

[[plugins]]
repo = 'thinca/vim-ref'
on_ft = ['php']

[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'tomlion/vim-solidity'

[[plugins]]
repo = 'stephpy/vim-yaml'
